---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    k9s_for_all_users: true
    command_shell: bash
  tasks:
    - name: Set download directory if install only for the user
      set_fact:
        k9s_runtime_dir: "{{ ansible_user_dir }}/bin"
      when: not k9s_for_all_users | bool

    - name: Set download directory for all users to use
      set_fact:
        k9s_runtime_dir: "/usr/local/bin"
      when: k9s_for_all_users | bool

    - name: Find the k9s file
      ansible.builtin.stat:
        path: "{{ k9s_runtime_dir }}/k9s"
      register: k9s_file

    - name: Print stat info
      debug:
        msg: "{{ k9s_file.stat }}"

    - name: Assert that k9s exists
      assert:
        that: k9s_file.stat.exists

    - name: Assert that k9s is executable
      assert:
        that: k9s_file.stat.executable
